### ISSUE TITLE
Sites that don't scroll at all because of extension. 

### ISSUE THREAD

**Issue by levibostian** [levibostian/DontTouchMyScroll-Chrome#3]
Some sites are not able to scroll correctly or scroll at all because of this extension. 

For current implementation, instead of removing scroll abilities in JS, you can replace with normal behavior?

**Comment by levibostian** [comment]
http://www.t-shirttv.com/shop-2/

**Comment by levibostian** [comment]
https://fabric.io/downloads/android

**Comment by mrkhdly** [comment]
http://flyovertechnology.com/base3/

**Comment by mrkhdly** [comment]
https://docs.google.com/spreadsheets 😿
